---
# Source: servicemonitors/templates/service-monitors.yaml
apiVersion: v1
kind: List
items:
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: prometheus-operator
    labels:
      k8s-app:  prometheus-operator
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: 
    selector:
      matchLabels:
        k8s-app: prometheus-operator
            
    endpoints:  
      - port: http
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: prometheus
    labels:
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: 
    selector:
      matchLabels:
        prometheus: k8s
        
    namespaceSelector:
      matchNames:
      - monitoring    
    endpoints:  
      - interval: 30s
        port: web
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: node-exporter
    labels:
      k8s-app:  node-exporter
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: node-exporter
        
    namespaceSelector:
      matchNames:
      - monitoring    
    endpoints:  
      - interval: 30s
        port: http-metrics
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kubelet
    labels:
      k8s-app:  kubelet
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kubelet
        
    namespaceSelector:
      matchNames:
      - kube-system    
    endpoints:  
      - honorLabels: true
        interval: 30s
        port: cadvisor
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kube-state-metrics
    labels:
      k8s-app:  kube-state-metrics
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kube-state-metrics
        
    namespaceSelector:
      matchNames:
      - monitoring    
    endpoints:  
      - honorLabels: true
        interval: 30s
        port: http-metrics
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kube-dns
    labels:
      k8s-app:  kube-dns
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kube-dns
        
    namespaceSelector:
      matchNames:
      - kube-system    
    endpoints:  
      - interval: 30s
        port: http-metrics-skydns
      - interval: 30s
        port: http-metrics-dnsmasq
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: alertmanager
    labels:
      k8s-app:  alertmanager
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: 
    selector:
      matchLabels:
        alertmanager: main
        
    namespaceSelector:
      matchNames:
      - monitoring    
    endpoints:  
      - interval: 30s
        port: web
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kube-apiserver
    labels:
      k8s-app:  apiserver
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: component
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
        
    namespaceSelector:
      matchNames:
      - default    
    endpoints:  
      - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        interval: 30s
        port: https
        scheme: https
        tlsConfig:
          caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          serverName: kubernetes
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kube-controller-manager
    labels:
      k8s-app:  kube-controller-manager
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kube-controller-manager
        
    namespaceSelector:
      matchNames:
      - kube-system    
    endpoints:  
      - interval: 30s
        port: http-metrics
      
- apiVersion: "monitoring.coreos.com/v1"
  kind: ServiceMonitor
  metadata:
    name: kube-scheduler
    labels:
      k8s-app:  kube-scheduler
      app: servicemonitors
      group: com.stakater.platform
      provider: stakater
      version: "2.2.0-rc.0"
      chart: "servicemonitors-1.0.1"
      release: "RELEASE-NAME"
      heritage: "Tiller"
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kube-scheduler
        
    namespaceSelector:
      matchNames:
      - kube-system    
    endpoints:  
      - interval: 30s
        port: http-metrics
      

