k8sServicemonitors:
  name: monitoring
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 2.2.0-rc.0

serviceMonitors:

- metadata:
    name: kube-controllers
    labels:
      k8sapp: kube-controllers
  spec:
    selector:
      matchLabels:
        k8s-app: kube-controllers
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 30s
      port: http-metrics
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    jobLabel: k8s-app
    namespaceSelector:
      matchNames:
      - kube-system
    


- metadata:
    name: prometheus-operator
    labels:      
      k8sapp: prometheus-operator
  spec:
    selector:
      matchLabels:
        k8s-app: prometheus-operator
    endpoints:
    - port: http

- metadata:
    name: prometheus
    labels:
      k8s-app: prometheus      
  spec:
    selector:
      matchLabels:
        prometheus: k8s
    namespaceSelector:
      matchNames:
      - monitoring
    endpoints:
    - port: web
      interval: 30s 

- metadata:
    name: node-exporter
    labels:
      k8sapp: node-exporter      
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: node-exporter
    namespaceSelector:
      matchNames:
      - monitoring
    endpoints:
    - port: http-metrics
      interval: 30s

- metadata:
    name: kubelet
    labels:
      k8sapp: kubelet      
  spec:
    jobLabel: k8s-app    
    selector:
      matchLabels:
        k8s-app: kubelet
    namespaceSelector:
      matchNames:
      - kube-system
    endpoints:
    - port: cadvisor
      interval: 30s
      honorLabels: true


- metadata:
    name: kube-state-metrics
    labels:
      k8sapp: kube-state-metrics      
  spec:
    jobLabel: k8s-app
    selector:
      matchLabels:
        k8s-app: kube-state-metrics
    namespaceSelector:
      matchNames:
      - monitoring
    endpoints:
    - port: http-metrics
      interval: 30s
      honorLabels: true

- metadata:
    name: kube-dns
    labels:
      k8sapp: kube-dns      
  spec:
    jobLabel: k8s-app    
    selector:
      matchLabels:
        k8s-app: kube-dns
    namespaceSelector:
      matchNames:
      - kube-system
    endpoints:
    - port: http-metrics-skydns
      interval: 30s
    - port: http-metrics-dnsmasq
      interval: 30s

- metadata:
    name: alertmanager
    labels:
      k8sapp: alertmanager      
  spec:
    selector:
      matchLabels:
        alertmanager: main
    namespaceSelector:
      matchNames:
      - monitoring
    endpoints:
    - port: web
      interval: 30s

- metadata:
    name: kube-apiserver
    labels:      
      k8sapp: apiserver
  spec:
    jobLabel: component
    selector:
      matchLabels:
        component: apiserver
        provider: kubernetes
    namespaceSelector:
      matchNames:
      - default
    endpoints:
    - port: https
      interval: 30s
      scheme: https
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

- metadata:
    name: kube-controller-manager
    labels:      
      k8sapp: kube-controller-manager
  spec:
    jobLabel: k8s-app    
    selector:
      matchLabels:
        k8s-app: kube-controller-manager
    namespaceSelector:
      matchNames:
      - kube-system
    endpoints:
    - port: http-metrics
      interval: 30s

- metadata:
    name: kube-scheduler
    labels:      
      k8sapp: kube-scheduler
  spec:
    jobLabel: k8s-app
    endpoints:
    - port: http-metrics
      interval: 30s
    selector:
      matchLabels:
        k8s-app: kube-scheduler
    namespaceSelector:
      matchNames:
      - kube-system
